stages:
- stage: foobarStage
  displayName: Foobar Stage
  jobs:
  - job: foobarJob
    displayName: Foobar Job
    steps:
    - task: CmdLine@2
      name: foobarTask
      displayName: Foobar Task
      inputs:
        script: |
          echo "Foobar!"
